phyton-django/56_User Permission Test/artikel/urls.py
from django.conf.urls import url

from .views import artikelIndexView, artikelAddView, artikelAddView2, otongView

urlpatterns = [
	url(r'^otong/$', otongView, name='otong'),	
	url(r'^add2/$', artikelAddView2, name='add2'),
	url(r'^add/$', artikelAddView, name='add'),
	url(r'^$', artikelIndexView, name='index'),
]

phyton-django/56_User Permission Test/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import index, loginView, logoutView

urlpatterns = [
	url(r'^artikel/', include('artikel.urls',namespace='artikel')),
	url(r'^logout/$', logoutView, name="logout"),
	url(r'^login/$', loginView, name="login"),
    url(r'^$', index, name="index"),
    url(r'^admin/', admin.site.urls),
]

phyton-django/56_User Permission Test/artikel/models.py
from django.db import models

# Create your models here.

phyton-django/56_User Permission Test/artikel/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
# Create your views here.


# custom check
@user_passes_test(lambda user: user.username == 'otong')
def otongView(request):
	return render(request,'artikel/otong.html',{})



# simple decorator check
@user_passes_test(lambda user: Group.objects.get(name='penulis') in user.groups.all())
def artikelAddView2(request):
	context = {
		'page_title':'Tambah Artikel View',
	}

	return render(request,'artikel/artikel_add.html',context)

# decorator check

def checkPenulis(user):
	test_group = Group.objects.get(name='penulis')
	user_group = user.groups.all()

	status = test_group in user_group
	print(status)
	return status


@user_passes_test(checkPenulis)
def artikelAddView(request):
	context = {
		'page_title':'Tambah Artikel View',
	}

	return render(request,'artikel/artikel_add.html',context)

# internal check
def artikelIndexView(request):
	context = {
		'page_title':'Artikel',
	}

	test_group = Group.objects.get(name='penulis')
	user_group = request.user.groups.all()
	

	template_name = None
	if test_group in user_group:
		# logika untuk user dalam group
		template_name = 'artikel/index_penulis.html'
	else:
		# logika untuk user diluar group
		template_name = 'artikel/index_pembaca.html'

	return render(request,template_name,context)

phyton-django/56_User Permission Test/mywebsite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# view method dengan internal permission checks
def index(request):
	context = {
		'page_title': 'Home',
	}


	template_name = None
	if request.user.is_authenticated():
		# logika untuk user
		template_name = 'index_user.html'
	else:
		# logika untuk anonymous
		template_name = 'index_anonymous.html'
	
	return render(request, template_name, context)


def loginView(request):
	context = {
		'page_title':'LOGIN',
	}
	user = None

	if request.method == "GET":
		if request.user.is_authenticated():
			# logika untuk user
			return redirect('index')
		else:
			# logika untuk anonymous
			return render(request, 'login.html', context)


	if request.method == "POST":
		
		username_login = request.POST['username']
		password_login = request.POST['password']
		
		user = authenticate(request, username=username_login, password=password_login)

		if user is not None:
			login(request, user)
			return redirect('index')
		else:
			return redirect('login')
	
	
@login_required
def logoutView(request):
	context = {
		'page_title':'logout'
	}

	if request.method == "POST":
		if request.POST["logout"] == "Submit":
			logout(request)

		return redirect('index')	


	return render(request, 'logout.html', context)

phyton-django/56_User Permission Test/artikel/templates/artikel/artikel_add.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>
	<h3>Selamat datang {{user}}</h3>
	<h3>Silahkan tambah artikel</h3>
</body>
</html>

phyton-django/56_User Permission Test/artikel/templates/artikel/index_pembaca.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<ul>
		<li><a href="{% url 'index' %}">Home</a></li>
		<li><a href="{% url 'artikel:add' %}">Add</a></li>
		<li><a href="{% url 'artikel:add2' %}">Add2</a></li>
	</ul>
	<h1>{{page_title}}</h1>

	<h3>Selamat datang {{user}}</h3>
	<h2>Silahkan membaca artikel kami</h2>

</body>
</html>

phyton-django/56_User Permission Test/artikel/templates/artikel/index_penulis.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<ul>
		<li><a href="{% url 'index' %}">Home</a></li>
		<li><a href="{% url 'artikel:add' %}">Add</a></li>
		<li><a href="{% url 'artikel:add2' %}">Add2</a></li>
	</ul>
	<h1>{{page_title}}</h1>

	<h3>Selamat datang {{user}}</h3>
	<h3>Anda adalah penulis hebat zaman ini</h3>
	<h4>Silahkan menulis</h4>
	<p>form untuk tambah artikel</p>

</body>
</html>

phyton-django/56_User Permission Test/artikel/templates/artikel/otong.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>OTONG</h1>
</body>
</html>

phyton-django/56_User Permission Test/templates/index_anonymous.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<ul>
		<li><a href="{% url 'artikel:index'%}">Artikel</a></li>
		<li><a href="{% url 'login' %}">Login</a></li>
	</ul>

	<h1>Selamat Datang di {{page_title}}</h1>
	<h3>Halo: {{user}}</h3>

</body>
</html>

phyton-django/56_User Permission Test/templates/index_user.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<ul>
		<li><a href="{% url 'artikel:index'%}">Artikel</a></li>
		<li><a href="{% url 'logout' %}">Logout</a></li>
	</ul>

	<h1>Selamat Datang di {{page_title}}</h1>
	<h3>Halo: {{user}}</h3>

</body>
</html>

phyton-django/56_User Permission Test/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>

	<form method="POST">
		{% csrf_token %}
		<label for="username">Username: </label>
		<input type="text" name="username" id="username">
		<br>
		<label for="password">Password: </label>
		<input type="password" name="password" id="password">
		<br>
		<button type="submit">Login</button>
	</form>
</body>
</html>

phyton-django/56_User Permission Test/templates/logout.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>

	<p>Apakah anda yakin akan logout?</p>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" name="logout">
	</form>
</body>
</html>