phyton-django/47_Detail View(Generic class based view)/blog/urls.py
from django.conf.urls import url
from django.views.generic import ListView, DetailView
from .views import ArtikelListView, ArtikelDetailView
from .models import Artikel


urlpatterns = [
	url(r'^(?P<penulis>\w+)/(?P<page>\d+)$', ArtikelListView.as_view(), name='list'),
	url(r'^(?P<penulis>\w+)/$', ArtikelListView.as_view(), name='list'),
	url(r'^detail/(?P<slug>[\w-]+)$', ArtikelDetailView.as_view(model=Artikel), name='detail'),
	# url(r'^detail/(?P<slug>[\w-]+)$', DetailView.as_view(model=Artikel), name='detail'),
	# url(r'^$', ListView.as_view(model=Artikel), name = 'list'),
]

phyton-django/47_Detail View(Generic class based view)/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^admin/', admin.site.urls),
]

phyton-django/47_Detail View(Generic class based view)/blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

class Artikel(models.Model):
	judul		= models.CharField(max_length=255)
	isi			= models.TextField()
	penulis		= models.CharField(max_length=255)
	publish		= models.DateTimeField(auto_now_add = True)
	update		= models.DateTimeField(auto_now = True)
	slug		= models.SlugField(blank=True, editable = False)

	def save(self):
		self.slug = slugify(self.judul)
		super(Artikel, self).save()


	def __str__(self):
		return "{}. {}".format(self.id, self.judul)

phyton-django/47_Detail View(Generic class based view)/blog/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView

from .models import Artikel

class ArtikelDetailView(DetailView):
	model = Artikel
	extra_context = {
		'page_title':'Detail Artikel',
	}

	def get_context_data(self, *args, **kwargs):
		self.kwargs.update(self.extra_context)
		artikel_lain = self.model.objects.exclude(slug=self.kwargs['slug'])
		self.kwargs.update({'artikel_lain':artikel_lain})
		kwargs = self.kwargs
		print(kwargs)
		return super().get_context_data(*args,**kwargs)



class ArtikelListView(ListView):
	model = Artikel
	ordering = ['update']
	# paginate_by = 2
	extra_context = {
		'page_title':'Blog List',
	}

	def get_queryset(self):
		if self.kwargs['penulis'] != 'all':
			self.queryset = self.model.objects.filter(penulis__iexact = self.kwargs['penulis'])
			self.kwargs.update({
				'penulis':self.kwargs['penulis'],
				})
		return super().get_queryset()

	def get_context_data(self,*args,**kwargs):
		self.kwargs.update(self.extra_context)
		kwargs = self.kwargs
		return super().get_context_data(*args,**kwargs)

phyton-django/47_Detail View(Generic class based view)/blog/templates/blog/artikel_detail.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>

	<h2>{{object.judul}}</h2>
	<span>Oleh: {{object.penulis}}, Ditulis : {{object.publish}}</span>
	<p>{{object.isi}}</p>
	<br>
	<a href="{% url 'blog:list' 'all' %}" title="">kembali</a>
	<br>
	<h3>Artikel lainnya:</h3>
	<ol>
		{% for artikel in artikel_lain %}
			<li>
				<a href="{% url 'blog:detail' artikel.slug %}" title="">{{artikel.judul}}</a> - oleh: {{artikel.penulis}}</li>		
		{% endfor %}
	</ol>
</body>
</html>

phyton-django/47_Detail View(Generic class based view)/blog/templates/blog/artikel_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>{{page_title}}</h1>
	<ol>
		{% for artikel in object_list %}
			<li>
				<a href="{% url 'blog:detail' artikel.slug %}" title="">{{artikel.judul}}</a> - oleh: {{artikel.penulis}}</li>		
		{% endfor %}
	</ol>
	
	{% if is_paginated %}
		{% if page_obj.has_previous %}
			<a href="{% url 'blog:list' penulis page_obj.previous_page_number %}" title="">&laquo</a>
		{% else %}
			<span>&laquo</span>
		{% endif %}
		

		{% for i in paginator.page_range %}
			<a href="{% url 'blog:list' penulis i %}" title="">
				{{i}}
			</a>
		{% endfor %}


		{% if page_obj.has_next %}
			<a href="{% url 'blog:list' penulis page_obj.next_page_number %}" title="">&raquo</a>
		{% else %}
			<span>&raquo</span>
		{% endif %}
	{% endif %}

	{# {% if is_paginated %} #}
			{# <li>object_list = {{object_list}}</li> #}
			{# <li>is_paginated = {{is_paginated}}</li> #}
			{# <li>page_obj = {{page_obj}}</li> #}
			{# <li>page_obj.number = {{page_number}}</li> #}
			{# <li>page_obj.has_next = {{page_obj.has_next}}</li> #}
			{# <li>page_obj.has_previous = {{page_obj.has_previous}}</li> #}
			{# <li>page_obj.has_other_pages = {{page_obj.has_other_pages}}</li> #}
			{# <li>page_obj.next_page_number = {{page_obj.next_page_number}}</li> #}
			{# <li>page_obj.previous_page_number = {{page_obj.previous_page_number}}</li> #}
			{# <li>page_obj.start_index = {{page_obj.start_index}}</li> #}
			{# <li>page_obj.end_index = {{page_obj.end_index}}</li> #}
			{# <li>paginator.count = {{paginator.count}}</li> #}
			{# <li>paginator.num_pages = {{paginator.num_pages}}</li> #}
			{# <li>paginator.page_range = {{paginator.page_range}}</li> #}
		{# {% endif %} #}
</body>
</html>

phyton-django/47_Detail View(Generic class based view)/blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>
</body>
</html>