phyton-django/35_Form Simple Validators/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^create/$', views.create, name='create'),
	url(r'^$', views.index, name='index'),
]

phyton-django/35_Form Simple Validators/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^blog/', include('blog.urls',namespace = 'blog')),
	url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
]

phyton-django/35_Form Simple Validators/blog/models.py
from django.db import models

# Create your models here.

class PostModel(models.Model):
	judul		= models.CharField(max_length = 20)
	body		= models.TextField()
	category	= models.CharField(max_length = 20)

	published	= models.DateTimeField(auto_now_add = True)
	updated		= models.DateTimeField(auto_now = True)

	def __str__(self):
		return "{}. {}".format(self.id, self.judul)

phyton-django/35_Form Simple Validators/blog/forms.py
from django import forms


class PostForm(forms.Form):
	judul		= forms.CharField(max_length = 20)
	body		= forms.CharField(
		widget = forms.Textarea
		)
	category	= forms.CharField(max_length = 20)

	def clean_judul(self):
		judul_input = self.cleaned_data.get('judul')

		if judul_input == "ucup":
			raise forms.ValidationError("ucup tidak boleh diposting")

		return judul_input

phyton-django/35_Form Simple Validators/blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.

from .forms import PostForm
from .models import PostModel

def index(request):
	posts = PostModel.objects.all()

	context = {
		'page_title':'List Post',
		'posts':posts,
	}

	return render(request,'blog/index.html',context)

def create(request):
	post_form = PostForm(request.POST or None)
	error = None
	if request.method == 'POST':

		if post_form.is_valid():
			PostModel.objects.create(
					judul 		= post_form.cleaned_data.get('judul'),
					body		= post_form.cleaned_data.get('body'),
					category	= post_form.cleaned_data.get('category'),
				)
			return HttpResponseRedirect("/blog/")
		else:
			error = post_form.errors



	context = {
		'page_title':'create post',
		'post_form':post_form,
		'error': error,
	}

	return render(request,'blog/create.html',context)

phyton-django/35_Form Simple Validators/mywebsite/views.py
from django.shortcuts import render


def index(request):
	context = {
		'page_title':'Home',
	}

	return render(request,'index.html',context)

phyton-django/35_Form Simple Validators/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block page_title %}
			
		{% endblock page_title %}
	</title>
</head>
<body>
	<ul>
		<li><a href="{% url 'index' %}">Home</a></li>
		<li><a href="{% url 'blog:index' %}">Blog</a></li>
		<ul>
			<li><a href="{% url 'blog:create' %}">Create</a></li>	
		</ul>
	</ul>


	{% block contents %}
		
	{% endblock contents %}

</body>
</html>

phyton-django/35_Form Simple Validators/templates/index.html
{% extends "base.html" %}

{% block page_title %}
	{{page_title}}
{% endblock page_title %}


{% block contents %}
	<h1>{{page_title}}</h1>
{% endblock contents %}